project:
  type: website

website:
  title: "Nerdy Bits"
  site-url: https://www.nerdybits.net
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/csuonereal # Changed to your username
      - icon: twitter
        href: https://twitter.com/ # Add your Twitter handle here

format:
  html:
    theme: cosmo
    css: styles.css
