project:
  type: website

website:
  title: "Nerdy Bits"
  site-url: https://www.nerdybits.net
  description: "A blog by Ulaş Tüzün exploring practical AI, software development, and other interesting topics in computer science."
  navbar:
    right:
      - about.qmd

format:
  html:
    theme: cosmo
    css: styles.css